# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('last_name',), 'verbose_name': 'Учень', 'verbose_name_plural': 'Учні'},
        ),
        migrations.AlterField(
            model_name='student',
            name='url',
            field=models.URLField(blank=True, default=django.utils.timezone.now, verbose_name='посилання на сторінку в соцмережі'),
            preserve_default=False,
        ),
    ]
