# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['last_name'], 'verbose_name': 'Вчитель', 'verbose_name_plural': 'Вчителі'},
        ),
    ]
